# Generated by Django 2.1.2 on 2018-10-09 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('resolution_w', models.IntegerField()),
                ('resolution_h', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('brightness', models.IntegerField()),
                ('module_w', models.DecimalField(decimal_places=2, max_digits=6)),
                ('module_h', models.DecimalField(decimal_places=2, max_digits=6)),
                ('module_res_w', models.IntegerField()),
                ('module_res_h', models.IntegerField()),
                ('power_max', models.DecimalField(decimal_places=2, max_digits=6)),
                ('power_typical', models.DecimalField(decimal_places=2, max_digits=6)),
                ('greyscale', models.IntegerField()),
                ('refresh_rate', models.IntegerField()),
                ('view_angle_hor', models.IntegerField()),
                ('view_angle_vert', models.IntegerField()),
                ('color_temp_min', models.IntegerField()),
                ('color_temp_max', models.IntegerField()),
                ('frame_frequency', models.IntegerField()),
                ('lifespan', models.IntegerField()),
                ('power_sypply', models.CharField(max_length=200)),
                ('ip_rating', models.CharField(max_length=200)),
                ('working_temp', models.CharField(max_length=200)),
                ('storage_temp', models.CharField(max_length=200)),
                ('working_humidity', models.CharField(max_length=200)),
                ('storage_humidity', models.CharField(max_length=200)),
                ('pixel_pitch', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fob_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='cabinet',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Vendor'),
        ),
    ]
