# Generated by Django 2.1.2 on 2018-10-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinet',
            name='power_sypply',
        ),
        migrations.AddField(
            model_name='cabinet',
            name='power_supply',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='ip_rating',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='model',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='storage_humidity',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='storage_temp',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='working_humidity',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='working_temp',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
