# Generated by Django 2.1.2 on 2018-10-09 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_auto_20181009_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Vendor', verbose_name='Вендор'),
        ),
    ]
